theme = "ace-documentation"

baseURL = 'https://azure.github.io/monitor-baseline-alerts'

languageCode = 'en-us'
title = 'Baseline Alerts for Monitoring in Azure'

pygmentsCodeFences = true
pygmentsStyle = "monokai"

[params]
disableReadmoreNav = true
menushortcutsnewtab = true
site_logo = "/monitor-baseline-alerts/media/img/abla-white.png"
toc = false

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[outputs]
home = ["HTML", "JSON", "RSS"]

[[menu.shortcuts]]
name = "Alerts for Azure Landing Zone"
url = "https://aka.ms/waf"
weight = 1

[[menu.shortcuts]]
name = "Source Code <i class='fab fa-github'></i>"
url = "https://github.com/Azure/alz-monitor"
weight = 10

[[menu.shortcuts]]
name = "Source Code <i class='fab fa-github'></i>"
url = "https://github.com/Azure/monitor-baseline-alerts"
weight = 10
